# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll for Web Designers
# email: your-email@example.com
description: "Companion blog to the Lynda.com course, Jekyll for Web Designers. This site is designed to present Jekyll to Web Designers in a clear, concise way, and provide a resource and reference for those that are new to Jekyll."
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://dangdewy.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com
tagline: "A basic guide to Jekyll"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
gems: [jekyll-paginate]
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title




theme: minima



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
